server:
  port: 9501
spring:
  application:
    name: microcloud.gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: MICROCLOUD_GROUP
        cluster-name: MuyanGateway
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator: # \u8D44\u6E90\u5B9A\u4F4D
          enabled: true # \u901A\u8FC7\u670D\u52A1\u53D1\u73B0\u67E5\u627E\u5176\u4ED6\u670D\u52A1